### PR TITLE
Topic_1

### PR DESCRIPTION
**Pull request by nicogarcia**
#### Ex 1 to 6

ShoppingCart may seem over-architectured because I tried to make it as a first version of the web service for the final project.
###### Features
- Discounts are applied over individual items or the total amount of the cart so that in the future this could be highlighted in a UI.
- New discounts can be created easily with a description and a calculating function.
- Notifications can be sent to any user.
- Notifications are event based, so they can be customized for each type of event.
###### Notes
- The project follows a layered structure consisting of DataAccess layer and Domain layer.
- Event loggers were thought to be used with DI in the future.
- Each entity has an independent serialization (toString()) that could be translated to a JSON object in the future.
- DiscountManager behaves like a Service Locator (for the final project its behaviour should be replaced with a tool provided by a framework)
- Repository pattern was used to be able to encapsulate data access routines in the future.

_Edit_
Developing the next topics I've found that IPaymentMethod interface has no amount or further information about the operation, so please consider it as a work to be done in next topics. Also DiscountManager will be made non-static.

### CODE REVIEW

**Comment by hernan-globant** [comment]
Above, see my comments and since that Shopping Cart modeling is an incremental design, please take them in consideration, to be fixed in the next topics. 
In general, a complete and detail well done design! Good job!

**Comment by nicogarcia** [comment]
Thanks for your comments! I fixed the errors in Topic 4, but you won't be able to see them since I haven't pushed Topic 1 files. If you want, I can push my local Topic_4 + Topic_1 branch.

**Comment by hernan-globant** [comment]
Great, since there were just findings considered as minor issues, it's not needed to update Topic1 branch, but need to be addressed and solved on the next topics, as you mentioned for Topic 4.
Please let me know if you have any other concern.

**Comment by nicogarcia** [comment]
Ok, thanks! I don't have any other concern!

**Pull request closed without merging**
